
# Generated by Django 4.2.2 on 2023-06-13 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('Alias_admin', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('CBU', models.IntegerField(unique=True)),
                ('Nombre_Apellido', models.CharField(max_length=45)),
                ('E_mail', models.EmailField(max_length=25)),
                ('Telefono', models.IntegerField()),
                ('Domicilio', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'db_table': 'Administrador',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_Categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': 'categorias de servicios',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('E_mail', models.EmailField(max_length=25)),
                ('Tipo_cliente', models.CharField(max_length=10)),
                ('Fecha_alta', models.DateField()),
                ('Nombre_Apellido', models.CharField(max_length=45)),
                ('DNI', models.IntegerField(unique=True)),
                ('Telefono', models.IntegerField()),
                ('Domicilio', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('Nro_mensaje', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Asunto', models.CharField(max_length=30)),
                ('Fecha', models.DateField()),
                ('Fecha_alta', models.DateField()),
                ('Descripción_mensaje', models.TextField(max_length=70)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'db_table': 'Mensajes',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('dni', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField(max_length=1000)),
                ('direccion', models.TextField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, max_length=100)),
                ('id_Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.categoria')),
            ],
            options={
                'verbose_name': 'servicios a realizar',
                'verbose_name_plural': 'servicios',
                'db_table': 'Servicio',
            },
        ),
        migrations.CreateModel(
            name='Propiedades',
            fields=[
                ('ID_propiedad', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Tipo_propiedad', models.CharField(max_length=10)),
                ('Ubicación', models.CharField(max_length=50)),
                ('superficie_m2', models.IntegerField()),
                ('Cant_ambientes', models.PositiveBigIntegerField()),
                ('Limite_ocupantes', models.PositiveBigIntegerField()),
                ('Permite_mascotas', models.BooleanField(default=True)),
                ('Apto_Crédito', models.BooleanField(default=True)),
                ('Tasación', models.DecimalField(decimal_places=2, default=2000, max_digits=10)),
                ('Precio_alquiler', models.DecimalField(decimal_places=2, default=2000, max_digits=10)),
                ('Alias_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.administrador')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'db_table': 'Propiedades',
            },
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('Nro_operación', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Tipo_operación', models.CharField(max_length=15)),
                ('Fecha_inicio', models.DateField()),
                ('Fecha_fin', models.DateField()),
                ('Comisión', models.DecimalField(decimal_places=2, default=2000, max_digits=10)),
                ('Motivo_pago', models.CharField(max_length=30)),
                ('Total_expensas', models.DecimalField(decimal_places=2, default=2000, max_digits=10)),
                ('Pago_total', models.DecimalField(decimal_places=2, default=2000, max_digits=10)),
                ('ID_propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.propiedades')),
            ],
            options={
                'verbose_name': 'Operacion',
                'verbose_name_plural': 'Operaciones',
                'db_table': 'Operacion',
            },
        ),
        migrations.CreateModel(
            name='Comprobante_Pago',
            fields=[
                ('Nro_comprobante', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Tipo_comprobante', models.CharField(max_length=25)),
                ('Descripción_operación', models.TextField(max_length=70)),
                ('Monto_pagado', models.DecimalField(decimal_places=2, default=2000, max_digits=10)),
                ('Nro_operación', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.operacion')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.cliente')),
            ],
            options={
                'verbose_name': 'Comprobante_pago',
                'verbose_name_plural': 'Comprobantes_pago',
                'db_table': 'Comprobantes',
            },
        ),
        migrations.CreateModel(
            name='Clientes_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_cliente', models.CharField(max_length=10)),
                ('Fecha_alta', models.DateField()),
                ('E_mail', models.EmailField(max_length=25)),
                ('Telefono', models.IntegerField()),
                ('Alias_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.administrador')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.cliente')),
            ],
            options={
                'verbose_name': 'Cliente_admin',
                'verbose_name_plural': 'Clientes_admin',
                'db_table': 'Clientes_admin',
            },
        ),
    ]
