# Generated by Django 4.2.2 on 2023-06-13 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes_admin',
            name='Alias_admin',
        ),
        migrations.RemoveField(
            model_name='clientes_admin',
            name='id_cliente',
        ),
        migrations.DeleteModel(
            name='Mensajes',
        ),
        migrations.RenameField(
            model_name='comprobante_pago',
            old_name='Descripción_operación',
            new_name='Descripcion_operacion',
        ),
        migrations.RenameField(
            model_name='comprobante_pago',
            old_name='Nro_operación',
            new_name='Nro_operacion',
        ),
        migrations.RenameField(
            model_name='operacion',
            old_name='Comisión',
            new_name='Comision',
        ),
        migrations.RenameField(
            model_name='operacion',
            old_name='Nro_operación',
            new_name='Nro_operacion',
        ),
        migrations.RenameField(
            model_name='operacion',
            old_name='Tipo_operación',
            new_name='Tipo_operacion',
        ),
        migrations.RemoveField(
            model_name='propiedades',
            name='Alias_admin',
        ),
        migrations.AddField(
            model_name='propiedades',
            name='id_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.cliente'),
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.DeleteModel(
            name='Clientes_admin',
        ),
    ]
